#!/bin/bash
RED="\e[31m"
GREEN="\e[32m"
RESET="\e[0m"

echo -e "${RED}----------BAD EXAMPLE 00----------${RESET}"
go run . "badexample00.txt"
echo -e "\n\n${RED}----------BAD EXAMPLE 01----------${RESET}"
go run . "badexample01.txt"
echo -e "\n\n${GREEN}------------EXAMPLE 00------------${RESET}"
go run . "example00.txt"
echo -e "\n\n${GREEN}------------EXAMPLE 01------------${RESET}"
go run . "example01.txt"
echo -e "\n\n${GREEN}------------EXAMPLE 02------------${RESET}"
go run . "example02.txt"
echo -e "\n\n${GREEN}------------EXAMPLE 03------------${RESET}"
go run . "example03.txt"
echo -e "\n\n${GREEN}------------EXAMPLE 04------------${RESET}"
go run . "example04.txt"
echo -e "\n\n${GREEN}------------EXAMPLE 05------------${RESET}"
go run . "example05.txt"
echo -e "\n\n${GREEN}------------EXAMPLE 06------------${RESET}"
go run . "example06.txt"
echo -e "\n\n${GREEN}------------EXAMPLE 07------------${RESET}"
go run . "example07.txt"